**
!Contracts/
!Contracts/EVA-ECS.Chat.Contracts/
!Contracts/EVA-ECS.Chat.Contracts/**
!Gateway/
!Gateway/**

**/.git
**/.github
**/.vs
**/.vscode
**/.idea
**/bin
**/obj
**/TestResults
**/nuget.config
**/*.user
**/*.nupkg
